project_id = "qjafzzejqksysgakbmhl"

[functions.ai-assistant]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.process-appointment-reminders]
verify_jwt = false
