// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjafzzejqksysgakbmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYWZ6emVqcWtzeXNnYWtibWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NDg3MTcsImV4cCI6MjA4ODAyNDcxN30.nyGMhuaNGriZ_QIY5QzlfMpB2PCiky0VlgZhyH6aZ2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});